### ISSUE TITLE
missing upper bounds

### ISSUE THREAD

**Issue by hvr** [mrkkrp/zip#10]
I notice that http://hackage.haskell.org/package/zip-0.1.0 leaves off several upper bounds which is worrying since many packages `zip` depends on are known to break their API significantly with major version bumps. Being able to state upper bounds is what the PVP is all about.

Moreover, the http://hackage.haskell.org/ frontpage states as guideline that

> -  All packages should follow the Package Versioning Policy (PVP).

And the PVP specifically states

> ## 3 Dependencies in Cabal
>
> When publishing a Cabal package, you should ensure that your dependencies in the `build-depends` field are accurate. **This means specifying not only lower bounds, but also upper bounds on every  dependency.**
>
> ...

Our Hackage/Cabal infrastructure is optimised toward this policy, and disregarding putting in accurate bounds causes overhead and additional work, since retrofitting missing upper bounds to *all* past releases is a lot more effort than just fixing up the most recent release (which sometimes even coincides with a new release anyway).

**Comment by mrkkrp** [comment]
Fixed, also fixed on Hackage: https://hackage.haskell.org/package/zip-0.1.0

I just realized that I unconditionally depend on `semigroups` here. Will this dependency break the build with GHC 8?

**Comment by hvr** [comment]
> I just realized that I unconditionally depend on `semigroups` here. Will this dependency break the build with GHC 8? (Although if it builds on Travis, it's probably OK.)

No, won't break, it's just redundant. the `semigroups` package becomes "transparent" when installed against base-4.9, i.e. it doesn't exposed `Data.Semigroups` and `Data.List.NonEmpty` in that case to avoid the nameclash with the modules that moved into `base-4.9`.

**Comment by mrkkrp** [comment]
@hvr, I've amended that. Now there should be enough upper bounds. Will mirror this on Hackage.
