### ISSUE TITLE
Unable to extract 4GB+ files from archive.

### ISSUE THREAD

**Issue by david-sledge** [mrkkrp/zip#111]
4GB+ files added to archives with this package are unable to be extracted. [Here](https://github.com/mrkkrp/zip/files/14593244/sandbox.tar.gz) is a minimal, complete, reproducible example demonstrating the issue. To run the example:

`tar -xvf sandbox.tar.gz && cd sandbox && docker build -t test . && docker run test`

**Comment by david-sledge** [comment]
The unzip utility might not be able to handle 4GB+ files, so I [redid the example](https://github.com/mrkkrp/zip/files/14593244/sandbox.tar.gz) using 7z to (try to) extract the file instead. To run the example:

`tar -xvf sandbox.tar.gz && cd sandbox && docker build -t test . && docker run test`

**Comment by mrkkrp** [comment]
Thanks for opening the issue! This should be fixed now, I will release version 2.0.1 with the fix today.
