### ISSUE TITLE
Behaviour of the library with malicious files

### ISSUE THREAD

**Issue by hce** [mrkkrp/zip#17]
Not a bug, just a question: I'm using the library to process files that users upload via a web interface. Now I'm wondering this:

How does the library behave if someone specifically crafts a malicous file:
  * Is it possible to get the library to consume an arbitrary amount of memory? For example, by making the meta data contained in the zip file ridiculously large?
  * Is it possible to cause an endless loop or get the library to consume a lot of CPU? For example, (just brainstorming) by creating stupid or excessively large huffman tables? Illegal offsets in the file table of contents?
  * Any other potential undesired effects? Unlikely due to haskell's type system...

**Comment by mrkkrp** [comment]
Good question, I need to think about it. It's certainly not possible to make meta-data larger than it can be (size of comment in stored as 2 byte value so it cannot be learger than `0xffff`, other things are handled similarily). I don't see how you can get it into endless loop too. Basically if file is not large, it will be traversed quickly, or it's end will be discovered anyway. This library does not ever read archive contents in memory. It stores operations and then you can think about it as one loop that reads bytes from source, modifies them if necessary and writes to destination file right away.

I would advise checking size of files. If you limit size of files, there is no way to attack you via the library (at least right now I don't see how it can be done).

**Comment by hce** [comment]
Okay, thank you very much for the response! Filesize is indeed limited to ~1GB. I will also have a look into the library and if I find anything, I'll report it here. IMHO we can close this ticket in the meantine.
