### ISSUE TITLE
Add proper support for CP1251 in case of generated Zip archive under Windows via 7zip

### ISSUE THREAD

**Issue by swamp-agr** [mrkkrp/zip#23]
* Main issue was https://github.com/jgm/zip-archive/issues/14.
* After switching from `zip-archive` to `zip` previous problem gone and there were no runtime exceptions after all.
* However, in case when existed archive contained cyrillic filenames after unpacking filename encoding recognized as CP437, instead of CP1251.

ER: 
```
ваз.txt
```

AR: 
```
óáº .txt
```

**Comment by mrkkrp** [comment]
If I remember correctly, there is a flag that should be set in local header of archive entry if file name is encoded in an encoding different from CP437 (as per standard, there are two “modes”, default is CP437 and with a flag we can write in UTF-8). The library is tested to recognize the flag and I myself use it with Russian file names without any problems. What happens here is that the existing archive probably contains no such flag, in which case the library performs decoding from CP437 (as it should) and gets garbage.

This is a defect in software that produced the archive. Knowing this, what action do you expect from me?

Note that this library works according to the [Zip specification](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT), it has no mention of CP1251 at all. You either use CP437 or set the flag and use UTF-8.

**Comment by mrkkrp** [comment]
Can you try to create an archive using modern version of 7Zip or something (create a Zip archive, not 7z though) and try to read it? It should work. I can test myself later if necessary.

**Comment by swamp-agr** [comment]
Yes, tomorrow I will try it and attach minimal test-case for further investigation.

**Comment by swamp-agr** [comment]
* Actually, I have no Windows right now. I asked my friend to generate simple Zip in the same way he did before.
* He mentioned that he made previous one with 7Zip.
* Here is a new one.
[vaz.zip](https://github.com/mrkkrp/zip/files/491598/vaz.zip)
* When I tried to look inside via `mc` correct filename displayed.
* When I tried to perform `unzip -oq vaz.zip` correct filename extracted.

**Comment by mrkkrp** [comment]
OK, thanks @swamp-agr I'll take a look.

**Comment by mrkkrp** [comment]
Hmm, it does not seem to look right on my system (Arch Linux):

```
mark@arch Downloads]$ unzip -v vaz.zip
Archive:  vaz.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Stored        0   0% 2016-09-25 13:55 00000000  ���.txt
--------          -------  ---                            -------
       0                0   0%                            1 file
```

FYI, the terminal has no problems displaying Cyrillic symbols, however, I'm getting this.

![invalid-encoding](https://cloud.githubusercontent.com/assets/8165792/18815261/d8cfc82e-833b-11e6-85b9-b46f043b189b.png)

This is unpacked via `unzip -oq vaz.zip` command. Arch Linux has usually latest versions of stuff, so I guess this `unzip` works correctly. What is the version of your `unzip`? What is the version of 7Zip application your friend used? I still think that it might be the case that 7Zip produced rather non-portable archive using host-OS encoding. I have no access to a Windows machine at this time as well, but maybe there are settings in 7Zip application that can be tweaked to produce a more portable archive?

**Comment by swamp-agr** [comment]
* My local settings are below:

```bash
andre@andre-an2-laptop ~ % uname -r
4.4.0-38-generic
andre@andre-an2-laptop ~ % cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
andre@andre-an2-laptop ~ % cd tmp
andre@andre-an2-laptop ~/tmp % unzip -oq vaz.zip
andre@andre-an2-laptop ~/tmp % ls *.txt
ваз.txt
andre@andre-an2-laptop ~/tmp % unzip -v
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip/ ;
see ftp://ftp.info-zip.org/pub/infozip/UnZip.html for other sites.

Compiled with gcc 5.2.1 20151119 for Unix (Linux ELF).

UnZip special compilation options:
        ACORN_FTYPE_NFS
        COPYRIGHT_CLEAN (PKZIP 0.9x unreducing method not supported)
        SET_DIR_ATTRIB
        SYMLINKS (symbolic links supported, if RTL and file system permit)
        TIMESTAMP
        UNIXBACKUP
        USE_EF_UT_TIME
        USE_UNSHRINK (PKZIP/Zip 1.x unshrinking method supported)
        USE_DEFLATE64 (PKZIP 4.x Deflate64(tm) supported)
        UNICODE_SUPPORT [wide-chars, char coding: UTF-8] (handle UTF-8 paths)
        LARGE_FILE_SUPPORT (large files over 2 GiB supported)
        ZIP64_SUPPORT (archives using Zip64 for large files supported)
        USE_BZIP2 (PKZIP 4.6+, using bzip2 lib version 1.0.6, 6-Sept-2010)
        VMS_TEXT_CONV
        WILD_STOP_AT_DIR
        [decryption, version 2.11 of 05 Jan 2007]

UnZip and ZipInfo environment options:
           UNZIP:  [none]
        UNZIPOPT:  [none]
         ZIPINFO:  [none]
      ZIPINFOOPT:  [none]
andre@andre-an2-laptop ~/tmp % echo $LANG
ru_RU.UTF-8
```

* 7zip version requested..

**Comment by swamp-agr** [comment]
* 7zip v.16.02

**Comment by mrkkrp** [comment]
For now I'll just point out to the relevant sections of the spec:

```
APPENDIX D - Language Encoding (EFS)
------------------------------------

D.1 The ZIP format has historically supported only the original IBM PC character
encoding set, commonly referred to as IBM Code Page 437.  This limits storing
file name characters to only those within the original MS-DOS range of values
and does not properly support file names in other character encodings, or
languages. To address this limitation, this specification will support the
following change.

D.2 If general purpose bit 11 is unset, the file name and comment should conform
to the original ZIP character encoding.  If general purpose bit 11 is set, the
filename and comment must support The Unicode Standard, Version 4.1.0 or
greater using the character encoding form defined by the UTF-8 storage
specification.  The Unicode Standard is published by the The Unicode
Consortium (www.unicode.org).  UTF-8 encoded data stored within ZIP files
is expected to not include a byte order mark (BOM).

D.3 Applications may choose to supplement this file name storage through the use
of the 0x0008 Extra Field.  Storage for this optional field is currently
undefined, however it will be used to allow storing extended information
on source or target encoding that may further assist applications with file
name, or file content encoding tasks.  Please contact PKWARE with any
requirements on how this field should be used.

D.4 The 0x0008 Extra Field storage may be used with either setting for general
purpose bit 11.  Examples of the intended usage for this field is to store
whether "modified-UTF-8" (JAVA) is used, or UTF-8-MAC.  Similarly, other
commonly used character encoding (code page) designations can be indicated
through this field.  Formalized values for use of the 0x0008 record remain
undefined at this time.  The definition for the layout of the 0x0008 field
will be published when available.  Use of the 0x0008 Extra Field provides
for storing data within a ZIP file in an encoding other than IBM Code
Page 437 or UTF-8.
```

Please check value of extended field `0x0008`. However note:

> Formalized values for use of the 0x0008 record remain undefined at this time.

So I won't include support for that unless it gets into the spec. As I said, it's well tested that the general purpose bit 11 is recognized. In fact I have a test case that generates file names randomly with and without Unicode symbols in them and writes them, then reads back. This is done 100 times with different file names, causing automatic enabling of the UTF-8 encoding when necessary. There may be no bug there. What you call “proper encoding recognition” maybe a custom feature of some sort, but since I aim to implement the Zip specs here, and it's unspecified there, it's out of the scope of the package. Indeed, the archive you provide is not portable because I, for one, could not extract it with correct file names. Compare this to the fact that this library always produces portable archives so they will be recognized anywhere (if not, open an issue — that's a bug) and so it expects input archives to be constructed according to the spec.

I'm sorry that you're running into these issues using the library, but I'm afraid I do not see it as a bug.

**Comment by swamp-agr** [comment]
* I've just tried output from your unzip command and it seems that you had ISO-8859-5 (Latin-5) as local encoding. 

```bash 
andre@andre-an2-laptop ~/tmp % echo '���' | enca          
Universal transformation format 8 bits; UTF-8
  Doubly-encoded to UTF-8 from ISO-8859-5
```

* If you change it from ISO-8859-5 to UTF-8 then you'll see correct filename instead of current.
* However, `zip` package recognize

**Comment by mrkkrp** [comment]
> you had ISO-8859-5 (Latin-5) as local encoding.

I have `en_US.UTF-8` as my locale. Anyway if it were in UTF-8 as it should, I wouldn't need to change anything. I have never needed to change anything to see Cyrillic file names, although I have quite a few of them.

**Comment by swamp-agr** [comment]
* OK, I will check `0x0008` value.
* Thank you, @mrkkrp.

**Comment by swamp-agr** [comment]
* `0x0008` record is empty.
* After a little investigation I found that filename decoding from CP1251 is [well known wrong behaviour of 7zip for Zip archives under a Windows](https://www.opennet.ru/tips/2494_zip_rus_patch.shtml).
* However, authors of `unzip` tool supported patch that fixed this issue.

**Comment by mrkkrp** [comment]
Closing then, because it's not a problem with `zip` package.
