### ISSUE TITLE
Zip64 handling yields corrupt central directory

### ISSUE THREAD

**Issue by rahulmutt** [mrkkrp/zip#30]
Run https://github.com/rahulmutt/zip-bench to reproduce. Clone and run `stack build` followed by `stack exec zip-bench`. It generates two files: Before.jar with 65534 entries and After.jar 65535 entries. Before.jar is valid, After.jar is corrupt.

```
$ unzip -l After.jar | head -n 6
Archive:  After.jar
warning [After.jar]:  76 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [After.jar]:  reported length of central directory is
  -76 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
  zipfile?).  Compensating...
```

**Comment by mrkkrp** [comment]
Can't reproduce it here:

```
~/projects/tests/zip-bench $ unzip -l After.jar | head -n 6
Archive:  After.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        1  2017-02-24 11:49   a1
        1  2017-02-24 11:49   a10
        1  2017-02-24 11:49   a100
```

**Comment by rahulmutt** [comment]
This was reproduced on Mac OS Sierra & El Capitan. On platform did you test it out? 

Can you try tweaking it to 65535 and 65536 and see if that will cause it? @jneira also reproed it on Windows (don't recall which version).

**Comment by mrkkrp** [comment]
Works with 65536 as well, I'm on Arch Linux (64 bit).

**Comment by mrkkrp** [comment]
These affected operating systems you mention, they are 64 bit or 32 bit?

**Comment by rahulmutt** [comment]
They're 64-bit. @jneira reports that on Win XP and Win 10, he's able to extract, but running the jar file fails. I'm wondering whether the difference in `unzip` program is causing different results? A better measure is probably the size of the generated jar file. On working systems, it should be 76 bytes less.

With the original unmodified program in the repo I shared,

After.jar    - 7514411 bytes
Before.jar - 7514220 bytes

**Comment by mrkkrp** [comment]
76 bytes is just size of Zip64 end of central directrory + end of central directory locator. Their presence is not an anomaly. If you have 65535 or more files in archive the feature is necessary because without it you can't have so many items in Zip archive.

This may be an issue with `unzip`, we need to find out version of this program that report error.

**Comment by mrkkrp** [comment]
I wonder if older `unzip` vesion just don't support Zip64 properly or are buggy. Please tell people who experience this try with 7Zip or something.

**Comment by mrkkrp** [comment]
> To specify the exact behaviour: it is possible to extract files properly from this invalid file, it's just that strict tools like java expect a perfectly formatted file and a slight deviation is enough to prevent executing the jar properly.

`zip` generates archives strictly according to Zip specification. Does Java support Zip64 in jars actually?

**Comment by rahulmutt** [comment]
That's the same question I had just now, and [this](https://blogs.oracle.com/xuemingshen/entry/zip64_support_for_4g_zipfile) blog post confirms that it's supported since Java 1.7 build 55 - rather recently. I'm using Java 8 right now and I'm still getting the error. I'll see if I can build a repro case that uses the Java Zip API (which is in turn used for executing jars).

**Comment by rahulmutt** [comment]
It turns out that the repro case I provided above is in fact valid, but there's another issue for Zip64 files  writing slightly invalid CD entries.

**Comment by mrkkrp** [comment]
Version 0.1.8 is on Hackage.

**Comment by rahulmutt** [comment]
Awesome, updated the dependency in Eta. Thanks for the prompt response!
