### ISSUE TITLE
Create a zip file without ZIP64 extension

### ISSUE THREAD

**Issue by mezzomondo** [mrkkrp/zip#33]
Hi,

I have a list of 10ish files in a folder all well under 300kB each. For compatibility reasons I need to create a zip file containing this folder without the ZIP64 extension but I can't find anywhere in the code a way to do it.

Is it possible?

(thanks)

**Comment by mrkkrp** [comment]
Zip64 is only enabled when it's necessary (either when there are too many files to store in vanilla Zip archive or if total size is too big).

**Comment by mezzomondo** [comment]
Ok, so there's no way to trigger (or better, un-trigger) it. Correct?

(because it seems to me that in my case neither there are too many files nor the total size is over 3.5MB)

Anyway thank you, I'll try to find some alternative.

**Comment by mrkkrp** [comment]
Wait, are you saying that Zip64 is enabled for you even though it shouldn't be enabled?

**Comment by mrkkrp** [comment]
To re-iterate:

* when you have < 0xffff files in your archive and total size is < 4 Gb, Zip64 is not enabled, you don't need to do a thing
* otherwise it's used automatically.

Unless you want to report a bug, I don't see how this may be a problem.

**Comment by mrkkrp** [comment]
I don't understand why you think you need to find an alternative, but the best option is probably `zip-archive` it doesn't supprot Zip64 and reads everything into memory, so unless you feed big files you should be safe. Closing.

**Comment by mezzomondo** [comment]
To be honest I don't absolutely want to find an alternative :-) I've got this problem (that is most likely a remote problem but completely out of my control) and I'm trying to find what options I have to solve it.
