### ISSUE TITLE
Stream create?

### ISSUE THREAD

**Issue by kanishka-azimi** [mrkkrp/zip#40]
Providing an option to generate zip file to a conduit stream instead of a filepath, such as https://hackage.haskell.org/package/zip-stream

Feel free to address or close, if you consider this out of scope. Thanks for considering.

**Comment by mrkkrp** [comment]
Please see: https://github.com/mrkkrp/zip/issues/13#issuecomment-195261943.

**Comment by kanishka-azimi** [comment]
Thanks for the quick response. I will close for now and use zip-stream. I am not sure if zip-stream will actually achieve bounded memory usage. I am hoping it does. If not, I will fallback to generating files with your library or possibly a process call.

**Comment by kanishka-azimi** [comment]
I might use the blindarchive approach with a conduit source wrapping the final handle if my local testing confirms that all steps preserve bounded memory/streaming.

I would definitely help grow your test suite if I end up using this library. I strangely enjoy writing tests and I am happy to see that you have strong coverage.
