### ISSUE TITLE
setModTime ordering issues

### ISSUE THREAD

**Issue by rahulmutt** [mrkkrp/zip#50]
```haskell
setModTime time selector
addEntry compress contents selector
```
will not set the modification time properly while
```haskell
addEntry compress contents selector
setModTime time selector
```
will set it properly.

Was this the intended behavior?

**Comment by mrkkrp** [comment]
Yes, the order in which you place the operations does matter. The approach is not declarative even though we do construct an intermediate representation of pending actions.

**Comment by mrkkrp** [comment]
Closing, as it’s not clear what else I should do ;-)
