### ISSUE TITLE
Very slow reads

### ISSUE THREAD

**Issue by srid** [mrkkrp/zip#54]
I'm trying to use this library to process Slack.com's JSON archive exports. I noticed that the reads (`getEntry`) are extremely slow. First I get the files listing and then call `getEntry` on each of them individually. Is this the performance to be expected, or is there some other way to make best use of this library?

**Comment by srid** [comment]
Oh nevermind. My fault; `withArchive` should be invoked once, with all actions happening in that monad.

**Comment by sboosali** [comment]
maybe this could be added to the readme as a "gotcha" (lile in an FAQ
section)?

**Comment by mrkkrp** [comment]
I’d merge a PR adding mention of that, but I think it might already be documented somewhere, maybe in Haddocks?
