### ISSUE TITLE
[wishlist] Flags to avoid C bindings, specifically libbz2

### ISSUE THREAD

**Issue by stephen-smith** [mrkkrp/zip#57]
I'm targeting an odd, "embeded-like" platform, where I can't upgrade libbz2[1], it provides libbz2.so.0.0.0.  I'm already doing my compilation in an ancient Debian Jessie VM to use a compatible glibc version, but even Jessie provides libbz2.so.1.  Would it be possible to add a cabal flag to avoid the (indirect) dependency on libbz2 by removing the (direct) dependency on bzlib-conduit?  I know the files I will want to process will not use bz2 compression, since I have other (Java) processes generating that I control.

[1] It's possible, but not easy.

**Comment by mrkkrp** [comment]
I’d accept a PR that adds the flag.
