### ISSUE TITLE
zip >= 1.5.0 has no documentation on Hackage

### ISSUE THREAD

**Issue by martijnbastiaan** [mrkkrp/zip#77]
* https://hackage.haskell.org/package/zip-1.4.1 (with docs)
* https://hackage.haskell.org/package/zip-1.5.0 (no docs)
* https://hackage.haskell.org/package/zip-1.7.0 (no docs)

**Comment by mrkkrp** [comment]
Thanks for the report. It appears that the environment that buids the docs doesn't have the `libbz2`:

https://hackage.haskell.org/package/zip-1.5.0/reports/3

I'm going to build and upload the docs manually.

**Comment by mrkkrp** [comment]
I have uploaded the docs for the version 1.7.0.
