### ISSUE TITLE
[question] Disabling C dependencies

### ISSUE THREAD

**Issue by epoberezkin** [mrkkrp/zip#87]
Thanks for the library!

I am probably doing something wrong to disable them, because I can still use these algorithms with these flags in .cabal file:

```
flag disable-bzip2
  description: removes dependency on bzip2 C library (zip package)
  manual: True
  default: True

flag disable-zstd
  description: Removes dependency on zstd C library (zip package)
  manual: True
  default: True
```

**Comment by mrkkrp** [comment]
If you put that in the `.cabal` file of your project, then you simply define these flags for your project. They have nothing to do with the flags of `zip`. What you probably want to do is:

```
cabal build --constraint="zip +disable-bzip2" --constraint="zip +disable-zstd"
```

or put that in your `cabal.project` file:

```
packages: .
constraints: zip +disable-bzip2 +disable-zstd
```

**Comment by epoberezkin** [comment]
Thanks you!!!
